apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-analytics
  name: backend-analytics
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5153
      targetPort: 5153
  selector:
    service: backend-analytics