apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:  
      service: backend
    template: 
      metadata:
        labels:
          service: backend
      spec:
        containers:
          - image: 260718118626.dkr.ecr.us-east-1.amazonaws.com/tulxecr
            name: backend
            imagePullPolicy: Always
            ports:
              - containerPort: 5153
            livenessProbe:
              httpGet:
                path: /health_check
                port: 5153
              initialDelaySeconds: 5
              timeoutSeconds: 2
            readinessProbe:
              httpGet:
                path: /readiness_check
                port: 5153
              initialDeplaySeconds: 5
              timeoutSeconds: 5
            resources:
              requests:
                memory: "1000Mi"
                cpu: "250m"
              limits:
                memory: "2000Mi"
                cpu: "500m"
            envFrom:
              - secretRef:
                  name: env-secret
              - configMapRef:
                  name: env-config
        restartPolicy: Always
