apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  selector:
    app.kubernetes.io/name: analytics-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153